In [6]:
import zipfile
local_zip = './text_to_sentiment.zip'
zip_ref = zipfile.ZipFile(local_zip)
zip_ref.extractall()
zip_ref.close()

In [7]:
import pandas as pd 
import numpy as np 

In [8]:
Data = pd.read_csv("./tweet_emotions.csv")
Data

tweet_id   sentiment  \
0      1956967341       empty   
1      1956967666     sadness   
2      1956967696     sadness   
3      1956967789  enthusiasm   
4      1956968416     neutral   
...           ...         ...   
39995  1753918954     neutral   
39996  1753919001        love   
39997  1753919005        love   
39998  1753919043   happiness   
39999  1753919049        love   

                                                 content  
0      @tiffanylue i know  i was listenin to bad habi...  
1      Layin n bed with a headache  ughhhh...waitin o...  
2                    Funeral ceremony...gloomy friday...  
3                   wants to hang out with friends SOON!  
4      @dannycastillo We want to trade with someone w...  
...                                                  ...  
39995                                   @JohnLloydTaylor  
39996                     Happy Mothers Day  All my love  
39997  Happy Mother's Day to all the mommies out ther...  
39998  @niariley WASSUP BEAUTIFUL!!! FOLLOW ME!!  PEE...  
39999  @mopedronin bullet train from tokyo    the gf ...  

[40000 rows x 3 columns]

In [9]:
Data.shape

(40000, 3)

In [10]:
emotions =[]
for x in Data.sentiment:
  emotions.append(x)
emotions = np.array(emotions)
print(emotions)

['empty' 'sadness' 'sadness' ... 'love' 'happiness' 'love']


In [11]:
content =[]
for x in Data.content:
  content.append(x)
content = np.array(content)
print(content)

['@tiffanylue i know  i was listenin to bad habit earlier and i started freakin at his part =['
 'Layin n bed with a headache  ughhhh...waitin on your call...'
 'Funeral ceremony...gloomy friday...' ...
 "Happy Mother's Day to all the mommies out there, be you woman or man as long as you're 'momma' to someone this is your day!"
 '@niariley WASSUP BEAUTIFUL!!! FOLLOW ME!!  PEEP OUT MY NEW HIT SINGLES WWW.MYSPACE.COM/IPSOHOT I DEF. WAT U IN THE VIDEO!!'
 '@mopedronin bullet train from tokyo    the gf and i have been visiting japan since thursday  vacation/sightseeing    gaijin godzilla']


In [12]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [13]:
tokenizer = Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(content)

In [14]:
#words index and print it 
word_index = tokenizer.word_index
#Generate sequences of the texts
sequences = tokenizer.texts_to_sequences(content)
#padding the sequences to a uniform lenght 
pad = pad_sequences(sequences, padding='post' )             #post: ignore the lasts words , pre : igrore the firsts 
print(word_index)

{'<OOV>': 1, 'i': 2, 'to': 3, 'the': 4, 'a': 5, 'my': 6, 'and': 7, 'you': 8, 'it': 9, 'is': 10, 'in': 11, 'for': 12, 'of': 13, 'me': 14, 'on': 15, 'have': 16, 'so': 17, 'that': 18, 'but': 19, 'just': 20, "i'm": 21, 'day': 22, 'with': 23, 'be': 24, 'at': 25, 'was': 26, 'not': 27, 'good': 28, 'all': 29, 'this': 30, 'now': 31, 'out': 32, 'up': 33, 'get': 34, 'like': 35, 'no': 36, 'are': 37, 'quot': 38, 'http': 39, 'go': 40, "it's": 41, 'do': 42, 'your': 43, 'today': 44, 'love': 45, 'work': 46, 'got': 47, 'too': 48, 'going': 49, 'happy': 50, 'lol': 51, 'from': 52, 'one': 53, 'time': 54, 'u': 55, 'know': 56, 'back': 57, 'what': 58, 'com': 59, 'im': 60, 'will': 61, 'really': 62, 'we': 63, 'am': 64, 'about': 65, "don't": 66, 'its': 67, 'see': 68, 'amp': 69, 'there': 70, 'had': 71, 'can': 72, "can't": 73, 'some': 74, 'if': 75, 'night': 76, 'new': 77, 'home': 78, 'think': 79, 'well': 80, '2': 81, 'thanks': 82, 'when': 83, 'want': 84, 'as': 85, 'how': 86, 'oh': 87, 'still': 88, 'off': 89, 'much'

In [15]:
print(pad.shape)

(40000, 37)


In [16]:
tokenizer_output = Tokenizer()
tokenizer_output.fit_on_texts(emotions)
#words index and print it 
word_index_outputs = tokenizer_output.word_index
#Generate sequences of the texts
sequences = tokenizer_output.texts_to_sequences(emotions)
#padding the sequences to a uniform lenght 
pad_output = pad_sequences(sequences, padding='post' )             #post: ignore the lasts words , pre : igrore the firsts 
print(word_index_outputs)
print(pad_output.shape)

{'neutral': 1, 'worry': 2, 'happiness': 3, 'sadness': 4, 'love': 5, 'surprise': 6, 'fun': 7, 'relief': 8, 'hate': 9, 'empty': 10, 'enthusiasm': 11, 'boredom': 12, 'anger': 13}
(40000, 1)


In [17]:
output = np.zeros((40000,13))
for i in range(40000):
  x=pad_output[i]
  output[i,x-1]=1
print(pad_output)
print("\n")
print(output)

[[10]
 [ 4]
 [ 4]
 ...
 [ 5]
 [ 3]
 [ 5]]


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [18]:
import tensorflow as tf 
from tensorflow import keras 
from tensorflow.keras import layers

#Build the model
model = keras.Sequential([
    layers.Embedding(48998,64,input_length=37),
    layers.Bidirectional(layers.LSTM(64,return_sequences=True)),
    layers.Bidirectional(layers.LSTM(64)),
    layers.Dense(128,activation='relu'),
    layers.Dense(13,activation='softmax')
])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 37, 64)            3135872   
                                                                 
 bidirectional (Bidirectiona  (None, 37, 128)          66048     
 l)                                                              
                                                                 
 bidirectional_1 (Bidirectio  (None, 128)              98816     
 nal)                                                            
                                                                 
 dense (Dense)               (None, 128)               16512     
                                                                 
 dense_1 (Dense)             (None, 13)                1677      
                                                                 
Total params: 3,318,925
Trainable params: 3,318,925
Non-

In [19]:
model.compile(loss="categorical_crossentropy",
              optimizer=keras.optimizers.Adam(lr=0.0001),
              metrics=["accuracy"]
     )

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [20]:
model.fit(pad,output,epochs=30)

Epoch 1/30
1250/1250 [==============================] - 25s 13ms/step - loss: 2.1532 - accuracy: 0.2458
Epoch 2/30
1250/1250 [==============================] - 16s 13ms/step - loss: 1.9442 - accuracy: 0.3364
Epoch 3/30
1250/1250 [==============================] - 17s 13ms/step - loss: 1.7855 - accuracy: 0.3960
Epoch 4/30
1250/1250 [==============================] - 16s 13ms/step - loss: 1.6202 - accuracy: 0.4528
Epoch 5/30
1250/1250 [==============================] - 16s 13ms/step - loss: 1.4508 - accuracy: 0.5127
Epoch 6/30
1250/1250 [==============================] - 19s 16ms/step - loss: 1.2989 - accuracy: 0.5755
Epoch 7/30
1250/1250 [==============================] - 18s 14ms/step - loss: 1.1729 - accuracy: 0.6258
Epoch 8/30
1250/1250 [==============================] - 16s 13ms/step - loss: 1.0691 - accuracy: 0.6640
Epoch 9/30
1250/1250 [==============================] - 17s 13ms/step - loss: 0.9862 - accuracy: 0.6926
Epoch 10/30
1250/1250 [==============================] - 16s 13m

In [35]:
test = ['i hate when you love others']
 

test_sequences = tokenizer.texts_to_sequences(test)
#padding the sequences to a uniform lenght 
test = pad_sequences(test_sequences, padding='post' , maxlen = 37 )             #post: ignore the lasts words , pre : igrore the firsts 

print(test.shape)
print(test)


(1, 37)
[[   2  165   83    8   45 1077    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]]


In [36]:
model.predict(test)

array([[0.04067664, 0.16346714, 0.01294472, 0.0343816 , 0.09411326,
        0.05188168, 0.00160019, 0.00908312, 0.56251925, 0.01854356,
        0.0011103 , 0.002636  , 0.0070426 ]], dtype=float32)

In [37]:
model.save_weights('saved_model/')  